// Code generated by go-abi. DO NOT EDIT.

package contracts

import (
	"encoding/binary"
	"errors"
	"io"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// entryPoint()
	EntryPointSelector = [4]byte{0xb0, 0xd6, 0x91, 0xfe}
	// execute(address,uint256,bytes)
	ExecuteSelector = [4]byte{0xb6, 0x1d, 0x27, 0xf6}
	// initialize(address,address)
	InitializeSelector = [4]byte{0x48, 0x5c, 0xc9, 0x55}
	// owner()
	OwnerSelector = [4]byte{0x8d, 0xa5, 0xcb, 0x5b}
	// validateUserOp((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes),bytes32,uint256)
	ValidateUserOpSelector = [4]byte{0x3a, 0x87, 0x1c, 0xdd}
)

// Big endian integer versions of function selectors
const (
	EntryPointID     = 2966852094
	ExecuteID        = 3055364086
	InitializeID     = 1214040405
	OwnerID          = 2376452955
	ValidateUserOpID = 981933277
)

const UserOperationStaticSize = 352

var _ abi.Tuple = (*UserOperation)(nil)

// UserOperation represents an ABI tuple
type UserOperation struct {
	Sender               common.Address
	Nonce                *big.Int
	InitCode             []byte
	CallData             []byte
	CallGasLimit         *big.Int
	VerificationGasLimit *big.Int
	PreVerificationGas   *big.Int
	MaxFeePerGas         *big.Int
	MaxPriorityFeePerGas *big.Int
	PaymasterAndData     []byte
	Signature            []byte
}

// EncodedSize returns the total encoded size of UserOperation
func (t UserOperation) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeBytes(t.InitCode)
	dynamicSize += abi.SizeBytes(t.CallData)
	dynamicSize += abi.SizeBytes(t.PaymasterAndData)
	dynamicSize += abi.SizeBytes(t.Signature)

	return UserOperationStaticSize + dynamicSize
}

// EncodeTo encodes UserOperation to ABI bytes in the provided buffer
func (value UserOperation) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := UserOperationStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Sender: address
	if _, err := abi.EncodeAddress(value.Sender, buf[0:]); err != nil {
		return 0, err
	}

	// Field Nonce: uint256
	if _, err := abi.EncodeUint256(value.Nonce, buf[32:]); err != nil {
		return 0, err
	}

	// Field InitCode: bytes
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeBytes(value.InitCode, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field CallData: bytes
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeBytes(value.CallData, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field CallGasLimit: uint256
	if _, err := abi.EncodeUint256(value.CallGasLimit, buf[128:]); err != nil {
		return 0, err
	}

	// Field VerificationGasLimit: uint256
	if _, err := abi.EncodeUint256(value.VerificationGasLimit, buf[160:]); err != nil {
		return 0, err
	}

	// Field PreVerificationGas: uint256
	if _, err := abi.EncodeUint256(value.PreVerificationGas, buf[192:]); err != nil {
		return 0, err
	}

	// Field MaxFeePerGas: uint256
	if _, err := abi.EncodeUint256(value.MaxFeePerGas, buf[224:]); err != nil {
		return 0, err
	}

	// Field MaxPriorityFeePerGas: uint256
	if _, err := abi.EncodeUint256(value.MaxPriorityFeePerGas, buf[256:]); err != nil {
		return 0, err
	}

	// Field PaymasterAndData: bytes
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[288+24:288+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeBytes(value.PaymasterAndData, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Signature: bytes
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[320+24:320+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeBytes(value.Signature, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes UserOperation to ABI bytes
func (value UserOperation) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes UserOperation from ABI bytes in the provided buffer
func (t *UserOperation) Decode(data []byte) (int, error) {
	if len(data) < 352 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 352
	// Decode static field Sender: address
	t.Sender, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Nonce: uint256
	t.Nonce, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field InitCode
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field InitCode")
		}
		t.InitCode, n, err = abi.DecodeBytes(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field CallData
	{
		offset := int(binary.BigEndian.Uint64(data[96+24 : 96+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field CallData")
		}
		t.CallData, n, err = abi.DecodeBytes(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field CallGasLimit: uint256
	t.CallGasLimit, _, err = abi.DecodeUint256(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode static field VerificationGasLimit: uint256
	t.VerificationGasLimit, _, err = abi.DecodeUint256(data[160:])
	if err != nil {
		return 0, err
	}
	// Decode static field PreVerificationGas: uint256
	t.PreVerificationGas, _, err = abi.DecodeUint256(data[192:])
	if err != nil {
		return 0, err
	}
	// Decode static field MaxFeePerGas: uint256
	t.MaxFeePerGas, _, err = abi.DecodeUint256(data[224:])
	if err != nil {
		return 0, err
	}
	// Decode static field MaxPriorityFeePerGas: uint256
	t.MaxPriorityFeePerGas, _, err = abi.DecodeUint256(data[256:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field PaymasterAndData
	{
		offset := int(binary.BigEndian.Uint64(data[288+24 : 288+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field PaymasterAndData")
		}
		t.PaymasterAndData, n, err = abi.DecodeBytes(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Signature
	{
		offset := int(binary.BigEndian.Uint64(data[320+24 : 320+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Signature")
		}
		t.Signature, n, err = abi.DecodeBytes(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*EntryPointCall)(nil)

// EntryPointCall represents the input arguments for entryPoint function
type EntryPointCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t EntryPointCall) GetMethodName() string {
	return "entryPoint"
}

// GetMethodID returns the function id
func (t EntryPointCall) GetMethodID() uint32 {
	return EntryPointID
}

// GetMethodSelector returns the function selector
func (t EntryPointCall) GetMethodSelector() [4]byte {
	return EntryPointSelector
}

// EncodeWithSelector encodes entryPoint arguments to ABI bytes including function selector
func (t EntryPointCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], EntryPointSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewEntryPointCall constructs a new EntryPointCall
func NewEntryPointCall() *EntryPointCall {
	return &EntryPointCall{}
}

const EntryPointReturnStaticSize = 32

var _ abi.Tuple = (*EntryPointReturn)(nil)

// EntryPointReturn represents an ABI tuple
type EntryPointReturn struct {
	Field1 common.Address
}

// EncodedSize returns the total encoded size of EntryPointReturn
func (t EntryPointReturn) EncodedSize() int {
	dynamicSize := 0

	return EntryPointReturnStaticSize + dynamicSize
}

// EncodeTo encodes EntryPointReturn to ABI bytes in the provided buffer
func (value EntryPointReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := EntryPointReturnStaticSize // Start dynamic data after static section
	// Field Field1: address
	if _, err := abi.EncodeAddress(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes EntryPointReturn to ABI bytes
func (value EntryPointReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes EntryPointReturn from ABI bytes in the provided buffer
func (t *EntryPointReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: address
	t.Field1, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*ExecuteCall)(nil)

const ExecuteCallStaticSize = 96

var _ abi.Tuple = (*ExecuteCall)(nil)

// ExecuteCall represents an ABI tuple
type ExecuteCall struct {
	Target common.Address
	Value  *big.Int
	Data   []byte
}

// EncodedSize returns the total encoded size of ExecuteCall
func (t ExecuteCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeBytes(t.Data)

	return ExecuteCallStaticSize + dynamicSize
}

// EncodeTo encodes ExecuteCall to ABI bytes in the provided buffer
func (value ExecuteCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := ExecuteCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Target: address
	if _, err := abi.EncodeAddress(value.Target, buf[0:]); err != nil {
		return 0, err
	}

	// Field Value: uint256
	if _, err := abi.EncodeUint256(value.Value, buf[32:]); err != nil {
		return 0, err
	}

	// Field Data: bytes
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeBytes(value.Data, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes ExecuteCall to ABI bytes
func (value ExecuteCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ExecuteCall from ABI bytes in the provided buffer
func (t *ExecuteCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 96
	// Decode static field Target: address
	t.Target, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Value: uint256
	t.Value, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Data
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Data")
		}
		t.Data, n, err = abi.DecodeBytes(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t ExecuteCall) GetMethodName() string {
	return "execute"
}

// GetMethodID returns the function id
func (t ExecuteCall) GetMethodID() uint32 {
	return ExecuteID
}

// GetMethodSelector returns the function selector
func (t ExecuteCall) GetMethodSelector() [4]byte {
	return ExecuteSelector
}

// EncodeWithSelector encodes execute arguments to ABI bytes including function selector
func (t ExecuteCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ExecuteSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewExecuteCall constructs a new ExecuteCall
func NewExecuteCall(
	target common.Address,
	value *big.Int,
	data []byte,
) *ExecuteCall {
	return &ExecuteCall{
		Target: target,
		Value:  value,
		Data:   data,
	}
}

// ExecuteReturn represents the output arguments for execute function
type ExecuteReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*InitializeCall)(nil)

const InitializeCallStaticSize = 64

var _ abi.Tuple = (*InitializeCall)(nil)

// InitializeCall represents an ABI tuple
type InitializeCall struct {
	Owner      common.Address
	EntryPoint common.Address
}

// EncodedSize returns the total encoded size of InitializeCall
func (t InitializeCall) EncodedSize() int {
	dynamicSize := 0

	return InitializeCallStaticSize + dynamicSize
}

// EncodeTo encodes InitializeCall to ABI bytes in the provided buffer
func (value InitializeCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := InitializeCallStaticSize // Start dynamic data after static section
	// Field Owner: address
	if _, err := abi.EncodeAddress(value.Owner, buf[0:]); err != nil {
		return 0, err
	}

	// Field EntryPoint: address
	if _, err := abi.EncodeAddress(value.EntryPoint, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes InitializeCall to ABI bytes
func (value InitializeCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes InitializeCall from ABI bytes in the provided buffer
func (t *InitializeCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field Owner: address
	t.Owner, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field EntryPoint: address
	t.EntryPoint, _, err = abi.DecodeAddress(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t InitializeCall) GetMethodName() string {
	return "initialize"
}

// GetMethodID returns the function id
func (t InitializeCall) GetMethodID() uint32 {
	return InitializeID
}

// GetMethodSelector returns the function selector
func (t InitializeCall) GetMethodSelector() [4]byte {
	return InitializeSelector
}

// EncodeWithSelector encodes initialize arguments to ABI bytes including function selector
func (t InitializeCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], InitializeSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewInitializeCall constructs a new InitializeCall
func NewInitializeCall(
	owner common.Address,
	entryPoint common.Address,
) *InitializeCall {
	return &InitializeCall{
		Owner:      owner,
		EntryPoint: entryPoint,
	}
}

// InitializeReturn represents the output arguments for initialize function
type InitializeReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*OwnerCall)(nil)

// OwnerCall represents the input arguments for owner function
type OwnerCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t OwnerCall) GetMethodName() string {
	return "owner"
}

// GetMethodID returns the function id
func (t OwnerCall) GetMethodID() uint32 {
	return OwnerID
}

// GetMethodSelector returns the function selector
func (t OwnerCall) GetMethodSelector() [4]byte {
	return OwnerSelector
}

// EncodeWithSelector encodes owner arguments to ABI bytes including function selector
func (t OwnerCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], OwnerSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewOwnerCall constructs a new OwnerCall
func NewOwnerCall() *OwnerCall {
	return &OwnerCall{}
}

const OwnerReturnStaticSize = 32

var _ abi.Tuple = (*OwnerReturn)(nil)

// OwnerReturn represents an ABI tuple
type OwnerReturn struct {
	Field1 common.Address
}

// EncodedSize returns the total encoded size of OwnerReturn
func (t OwnerReturn) EncodedSize() int {
	dynamicSize := 0

	return OwnerReturnStaticSize + dynamicSize
}

// EncodeTo encodes OwnerReturn to ABI bytes in the provided buffer
func (value OwnerReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := OwnerReturnStaticSize // Start dynamic data after static section
	// Field Field1: address
	if _, err := abi.EncodeAddress(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes OwnerReturn to ABI bytes
func (value OwnerReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes OwnerReturn from ABI bytes in the provided buffer
func (t *OwnerReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: address
	t.Field1, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*ValidateUserOpCall)(nil)

const ValidateUserOpCallStaticSize = 96

var _ abi.Tuple = (*ValidateUserOpCall)(nil)

// ValidateUserOpCall represents an ABI tuple
type ValidateUserOpCall struct {
	UserOp     UserOperation
	UserOpHash [32]byte
	Field3     *big.Int
}

// EncodedSize returns the total encoded size of ValidateUserOpCall
func (t ValidateUserOpCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += t.UserOp.EncodedSize()

	return ValidateUserOpCallStaticSize + dynamicSize
}

// EncodeTo encodes ValidateUserOpCall to ABI bytes in the provided buffer
func (value ValidateUserOpCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := ValidateUserOpCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field UserOp: (address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.UserOp.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field UserOpHash: bytes32
	if _, err := abi.EncodeBytes32(value.UserOpHash, buf[32:]); err != nil {
		return 0, err
	}

	// Field Field3: uint256
	if _, err := abi.EncodeUint256(value.Field3, buf[64:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes ValidateUserOpCall to ABI bytes
func (value ValidateUserOpCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidateUserOpCall from ABI bytes in the provided buffer
func (t *ValidateUserOpCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 96
	// Decode dynamic field UserOp
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field UserOp")
		}
		n, err = t.UserOp.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field UserOpHash: bytes32
	t.UserOpHash, _, err = abi.DecodeBytes32(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Field3: uint256
	t.Field3, _, err = abi.DecodeUint256(data[64:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t ValidateUserOpCall) GetMethodName() string {
	return "validateUserOp"
}

// GetMethodID returns the function id
func (t ValidateUserOpCall) GetMethodID() uint32 {
	return ValidateUserOpID
}

// GetMethodSelector returns the function selector
func (t ValidateUserOpCall) GetMethodSelector() [4]byte {
	return ValidateUserOpSelector
}

// EncodeWithSelector encodes validateUserOp arguments to ABI bytes including function selector
func (t ValidateUserOpCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ValidateUserOpSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewValidateUserOpCall constructs a new ValidateUserOpCall
func NewValidateUserOpCall(
	userOp UserOperation,
	userOpHash [32]byte,
	field3 *big.Int,
) *ValidateUserOpCall {
	return &ValidateUserOpCall{
		UserOp:     userOp,
		UserOpHash: userOpHash,
		Field3:     field3,
	}
}

const ValidateUserOpReturnStaticSize = 32

var _ abi.Tuple = (*ValidateUserOpReturn)(nil)

// ValidateUserOpReturn represents an ABI tuple
type ValidateUserOpReturn struct {
	ValidationData *big.Int
}

// EncodedSize returns the total encoded size of ValidateUserOpReturn
func (t ValidateUserOpReturn) EncodedSize() int {
	dynamicSize := 0

	return ValidateUserOpReturnStaticSize + dynamicSize
}

// EncodeTo encodes ValidateUserOpReturn to ABI bytes in the provided buffer
func (value ValidateUserOpReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := ValidateUserOpReturnStaticSize // Start dynamic data after static section
	// Field ValidationData: uint256
	if _, err := abi.EncodeUint256(value.ValidationData, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes ValidateUserOpReturn to ABI bytes
func (value ValidateUserOpReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidateUserOpReturn from ABI bytes in the provided buffer
func (t *ValidateUserOpReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field ValidationData: uint256
	t.ValidationData, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}
