// Code generated by go-abi. DO NOT EDIT.

package testdata

import (
	"io"
	"math/big"

	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// counter()
	CounterSelector = [4]byte{0x61, 0xbc, 0x22, 0x1a}
	// decrement()
	DecrementSelector = [4]byte{0x2b, 0xae, 0xce, 0xb7}
	// increment()
	IncrementSelector = [4]byte{0xd0, 0x9d, 0xe0, 0x8a}
)

// Big endian integer versions of function selectors
const (
	CounterID   = 1639719450
	DecrementID = 732876471
	IncrementID = 3500007562
)

var _ abi.Method = (*CounterCall)(nil)

// CounterCall represents the input arguments for counter function
type CounterCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t CounterCall) GetMethodName() string {
	return "counter"
}

// GetMethodID returns the function id
func (t CounterCall) GetMethodID() uint32 {
	return CounterID
}

// GetMethodSelector returns the function selector
func (t CounterCall) GetMethodSelector() [4]byte {
	return CounterSelector
}

// EncodeWithSelector encodes counter arguments to ABI bytes including function selector
func (t CounterCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], CounterSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewCounterCall constructs a new CounterCall
func NewCounterCall() *CounterCall {
	return &CounterCall{}
}

const CounterReturnStaticSize = 32

var _ abi.Tuple = (*CounterReturn)(nil)

// CounterReturn represents an ABI tuple
type CounterReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of CounterReturn
func (t CounterReturn) EncodedSize() int {
	dynamicSize := 0

	return CounterReturnStaticSize + dynamicSize
}

// EncodeTo encodes CounterReturn to ABI bytes in the provided buffer
func (value CounterReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := CounterReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes CounterReturn to ABI bytes
func (value CounterReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes CounterReturn from ABI bytes in the provided buffer
func (t *CounterReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*DecrementCall)(nil)

// DecrementCall represents the input arguments for decrement function
type DecrementCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t DecrementCall) GetMethodName() string {
	return "decrement"
}

// GetMethodID returns the function id
func (t DecrementCall) GetMethodID() uint32 {
	return DecrementID
}

// GetMethodSelector returns the function selector
func (t DecrementCall) GetMethodSelector() [4]byte {
	return DecrementSelector
}

// EncodeWithSelector encodes decrement arguments to ABI bytes including function selector
func (t DecrementCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DecrementSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewDecrementCall constructs a new DecrementCall
func NewDecrementCall() *DecrementCall {
	return &DecrementCall{}
}

// DecrementReturn represents the output arguments for decrement function
type DecrementReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*IncrementCall)(nil)

// IncrementCall represents the input arguments for increment function
type IncrementCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t IncrementCall) GetMethodName() string {
	return "increment"
}

// GetMethodID returns the function id
func (t IncrementCall) GetMethodID() uint32 {
	return IncrementID
}

// GetMethodSelector returns the function selector
func (t IncrementCall) GetMethodSelector() [4]byte {
	return IncrementSelector
}

// EncodeWithSelector encodes increment arguments to ABI bytes including function selector
func (t IncrementCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], IncrementSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewIncrementCall constructs a new IncrementCall
func NewIncrementCall() *IncrementCall {
	return &IncrementCall{}
}

// IncrementReturn represents the output arguments for increment function
type IncrementReturn struct {
	abi.EmptyTuple
}
