// Code generated by go-abi. DO NOT EDIT.

package testdata

import (
	"io"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// counterInstance()
	CounterInstanceSelector = [4]byte{0xae, 0xf3, 0x8e, 0x72}
	// decrementCounter()
	DecrementCounterSelector = [4]byte{0xf5, 0xc5, 0xad, 0x83}
	// getCounterValue()
	GetCounterValueSelector = [4]byte{0x72, 0x14, 0x2b, 0x89}
	// incrementCounter()
	IncrementCounterSelector = [4]byte{0x5b, 0x34, 0xb9, 0x66}
)

// Big endian integer versions of function selectors
const (
	CounterInstanceID  = 2935197298
	DecrementCounterID = 4123372931
	GetCounterValueID  = 1913924489
	IncrementCounterID = 1530181990
)

var _ abi.Method = (*CounterInstanceCall)(nil)

// CounterInstanceCall represents the input arguments for counterInstance function
type CounterInstanceCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t CounterInstanceCall) GetMethodName() string {
	return "counterInstance"
}

// GetMethodID returns the function id
func (t CounterInstanceCall) GetMethodID() uint32 {
	return CounterInstanceID
}

// GetMethodSelector returns the function selector
func (t CounterInstanceCall) GetMethodSelector() [4]byte {
	return CounterInstanceSelector
}

// EncodeWithSelector encodes counterInstance arguments to ABI bytes including function selector
func (t CounterInstanceCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], CounterInstanceSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewCounterInstanceCall constructs a new CounterInstanceCall
func NewCounterInstanceCall() *CounterInstanceCall {
	return &CounterInstanceCall{}
}

const CounterInstanceReturnStaticSize = 32

var _ abi.Tuple = (*CounterInstanceReturn)(nil)

// CounterInstanceReturn represents an ABI tuple
type CounterInstanceReturn struct {
	Field1 common.Address
}

// EncodedSize returns the total encoded size of CounterInstanceReturn
func (t CounterInstanceReturn) EncodedSize() int {
	dynamicSize := 0

	return CounterInstanceReturnStaticSize + dynamicSize
}

// EncodeTo encodes CounterInstanceReturn to ABI bytes in the provided buffer
func (value CounterInstanceReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := CounterInstanceReturnStaticSize // Start dynamic data after static section
	// Field Field1: address
	if _, err := abi.EncodeAddress(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes CounterInstanceReturn to ABI bytes
func (value CounterInstanceReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes CounterInstanceReturn from ABI bytes in the provided buffer
func (t *CounterInstanceReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: address
	t.Field1, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*DecrementCounterCall)(nil)

// DecrementCounterCall represents the input arguments for decrementCounter function
type DecrementCounterCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t DecrementCounterCall) GetMethodName() string {
	return "decrementCounter"
}

// GetMethodID returns the function id
func (t DecrementCounterCall) GetMethodID() uint32 {
	return DecrementCounterID
}

// GetMethodSelector returns the function selector
func (t DecrementCounterCall) GetMethodSelector() [4]byte {
	return DecrementCounterSelector
}

// EncodeWithSelector encodes decrementCounter arguments to ABI bytes including function selector
func (t DecrementCounterCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DecrementCounterSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewDecrementCounterCall constructs a new DecrementCounterCall
func NewDecrementCounterCall() *DecrementCounterCall {
	return &DecrementCounterCall{}
}

// DecrementCounterReturn represents the output arguments for decrementCounter function
type DecrementCounterReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*GetCounterValueCall)(nil)

// GetCounterValueCall represents the input arguments for getCounterValue function
type GetCounterValueCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t GetCounterValueCall) GetMethodName() string {
	return "getCounterValue"
}

// GetMethodID returns the function id
func (t GetCounterValueCall) GetMethodID() uint32 {
	return GetCounterValueID
}

// GetMethodSelector returns the function selector
func (t GetCounterValueCall) GetMethodSelector() [4]byte {
	return GetCounterValueSelector
}

// EncodeWithSelector encodes getCounterValue arguments to ABI bytes including function selector
func (t GetCounterValueCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], GetCounterValueSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewGetCounterValueCall constructs a new GetCounterValueCall
func NewGetCounterValueCall() *GetCounterValueCall {
	return &GetCounterValueCall{}
}

const GetCounterValueReturnStaticSize = 32

var _ abi.Tuple = (*GetCounterValueReturn)(nil)

// GetCounterValueReturn represents an ABI tuple
type GetCounterValueReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of GetCounterValueReturn
func (t GetCounterValueReturn) EncodedSize() int {
	dynamicSize := 0

	return GetCounterValueReturnStaticSize + dynamicSize
}

// EncodeTo encodes GetCounterValueReturn to ABI bytes in the provided buffer
func (value GetCounterValueReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := GetCounterValueReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes GetCounterValueReturn to ABI bytes
func (value GetCounterValueReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetCounterValueReturn from ABI bytes in the provided buffer
func (t *GetCounterValueReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*IncrementCounterCall)(nil)

// IncrementCounterCall represents the input arguments for incrementCounter function
type IncrementCounterCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t IncrementCounterCall) GetMethodName() string {
	return "incrementCounter"
}

// GetMethodID returns the function id
func (t IncrementCounterCall) GetMethodID() uint32 {
	return IncrementCounterID
}

// GetMethodSelector returns the function selector
func (t IncrementCounterCall) GetMethodSelector() [4]byte {
	return IncrementCounterSelector
}

// EncodeWithSelector encodes incrementCounter arguments to ABI bytes including function selector
func (t IncrementCounterCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], IncrementCounterSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewIncrementCounterCall constructs a new IncrementCounterCall
func NewIncrementCounterCall() *IncrementCounterCall {
	return &IncrementCounterCall{}
}

// IncrementCounterReturn represents the output arguments for incrementCounter function
type IncrementCounterReturn struct {
	abi.EmptyTuple
}
