direction: down

# entities
prepare proposal
check tx handler
comet bft
rpc call
broadcast
rebroadcast\ncallback: { shape: diamond }
evm mempool: {
    direction: left

    # entities
    ext mempool interface impl
    cosmos priority nonce mempool
    tx pool: {
        direction: left

        # entities
        queued\ntransactions
        pending\ntransactions
        tx pool\ninterface
        reset loop\n(evicts from\nqueued and\npending txs)
        promotion: {shape: diamond }
        filter: { shape: diamond }
        
        # edges
        filter -> queued\ntransactions: add nonce\ngapped txs
        filter -> pending\ntransactions: add\nexecutable txs
        promotion -> pending\ntransactions: promote tx
        queued\ntransactions -> promotion: check closed gap\nand promote tx
        pending\ntransactions -> tx pool\ninterface: get txs for\nblock building
    }
    
    # edges
    tx pool.tx pool\ninterface -> ext mempool interface impl: get txs for\nblock building
    
    cosmos priority nonce mempool -> ext mempool interface impl: get txs for\nblock building

    ext mempool interface impl -> tx pool.tx pool\ninterface: success/nonce gap failure:\nadd valid evm txs
    ext mempool interface impl -> tx pool.tx pool\ninterface: recheck tx\neviction
    ext mempool interface impl -> cosmos priority nonce mempool: add\ncosmos txs
}

# edges
rebroadcast\ncallback -> comet bft: rebroadcast\nrebuilt tx

evm mempool.tx pool.promotion -> rebroadcast\ncallback: call rebroadcast\ncallback
evm mempool.ext mempool interface impl -> prepare proposal: get txs for\nblock building

comet bft -> broadcast: success:\nbroadcast tx
comet bft -> check tx handler: send tx for validation
comet bft -> check tx handler: send tx again\nfor recheck

check tx handler -> rpc call: queued\nsuccess response
check tx handler -> comet bft: success: broadcast\nand add to mempool
check tx handler -> comet bft: recheck tx complete\nfailure: discard from pool
check tx handler -> evm mempool.ext mempool interface impl: complete failure:\nremove from pending
check tx handler -> evm mempool.ext mempool interface impl: nonce gap failure:\nadd transaction
check tx handler -> evm mempool.ext mempool interface impl: success:\nadd txs
check tx handler -> evm mempool.ext mempool interface impl: recheck tx complete\nfailure: eviction