// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: cosmos/evm/ibc/clients/v1/query.proto

package clientsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_ClientPrecompile_FullMethodName  = "/cosmos.evm.ibc.clients.v1.Query/ClientPrecompile"
	Query_ClientPrecompiles_FullMethodName = "/cosmos.evm.ibc.clients.v1.Query/ClientPrecompiles"
	Query_Params_FullMethodName            = "/cosmos.evm.ibc.clients.v1.Query/Params"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// ClientPrecompile returns the registered client precompile for a given
	// client.
	ClientPrecompile(ctx context.Context, in *QueryClientPrecompileRequest, opts ...grpc.CallOption) (*QueryClientPrecompileResponse, error)
	// ClientPrecompiles returns all the ClientPrecompile values.
	ClientPrecompiles(ctx context.Context, in *QueryClientPrecompilesRequest, opts ...grpc.CallOption) (*QueryClientPrecompilesResponse, error)
	// Params returns the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ClientPrecompile(ctx context.Context, in *QueryClientPrecompileRequest, opts ...grpc.CallOption) (*QueryClientPrecompileResponse, error) {
	out := new(QueryClientPrecompileResponse)
	err := c.cc.Invoke(ctx, Query_ClientPrecompile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClientPrecompiles(ctx context.Context, in *QueryClientPrecompilesRequest, opts ...grpc.CallOption) (*QueryClientPrecompilesResponse, error) {
	out := new(QueryClientPrecompilesResponse)
	err := c.cc.Invoke(ctx, Query_ClientPrecompiles_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// ClientPrecompile returns the registered client precompile for a given
	// client.
	ClientPrecompile(context.Context, *QueryClientPrecompileRequest) (*QueryClientPrecompileResponse, error)
	// ClientPrecompiles returns all the ClientPrecompile values.
	ClientPrecompiles(context.Context, *QueryClientPrecompilesRequest) (*QueryClientPrecompilesResponse, error)
	// Params returns the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) ClientPrecompile(context.Context, *QueryClientPrecompileRequest) (*QueryClientPrecompileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientPrecompile not implemented")
}
func (UnimplementedQueryServer) ClientPrecompiles(context.Context, *QueryClientPrecompilesRequest) (*QueryClientPrecompilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientPrecompiles not implemented")
}
func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_ClientPrecompile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClientPrecompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClientPrecompile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ClientPrecompile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClientPrecompile(ctx, req.(*QueryClientPrecompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClientPrecompiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClientPrecompilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClientPrecompiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_ClientPrecompiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClientPrecompiles(ctx, req.(*QueryClientPrecompilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.ibc.clients.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientPrecompile",
			Handler:    _Query_ClientPrecompile_Handler,
		},
		{
			MethodName: "ClientPrecompiles",
			Handler:    _Query_ClientPrecompiles_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/ibc/clients/v1/query.proto",
}
