// Code generated by go-abi. DO NOT EDIT.

package reverter

import (
	"io"
	"math/big"

	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// run()
	RunSelector = [4]byte{0xc0, 0x40, 0x62, 0x26}
	// transferFunds(bytes32,uint256)
	TransferFundsSelector = [4]byte{0x79, 0x38, 0x8e, 0x94}
)

// Big endian integer versions of function selectors
const (
	RunID           = 3225444902
	TransferFundsID = 2033749652
)

var _ abi.Method = (*RunCall)(nil)

// RunCall represents the input arguments for run function
type RunCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t RunCall) GetMethodName() string {
	return "run"
}

// GetMethodID returns the function id
func (t RunCall) GetMethodID() uint32 {
	return RunID
}

// GetMethodSelector returns the function selector
func (t RunCall) GetMethodSelector() [4]byte {
	return RunSelector
}

// EncodeWithSelector encodes run arguments to ABI bytes including function selector
func (t RunCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], RunSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewRunCall constructs a new RunCall
func NewRunCall() *RunCall {
	return &RunCall{}
}

// RunReturn represents the output arguments for run function
type RunReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*TransferFundsCall)(nil)

const TransferFundsCallStaticSize = 64

var _ abi.Tuple = (*TransferFundsCall)(nil)

// TransferFundsCall represents an ABI tuple
type TransferFundsCall struct {
	Salt [32]byte
	V    *big.Int
}

// EncodedSize returns the total encoded size of TransferFundsCall
func (t TransferFundsCall) EncodedSize() int {
	dynamicSize := 0

	return TransferFundsCallStaticSize + dynamicSize
}

// EncodeTo encodes TransferFundsCall to ABI bytes in the provided buffer
func (value TransferFundsCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransferFundsCallStaticSize // Start dynamic data after static section
	// Field Salt: bytes32
	if _, err := abi.EncodeBytes32(value.Salt, buf[0:]); err != nil {
		return 0, err
	}

	// Field V: uint256
	if _, err := abi.EncodeUint256(value.V, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransferFundsCall to ABI bytes
func (value TransferFundsCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferFundsCall from ABI bytes in the provided buffer
func (t *TransferFundsCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field Salt: bytes32
	t.Salt, _, err = abi.DecodeBytes32(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field V: uint256
	t.V, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TransferFundsCall) GetMethodName() string {
	return "transferFunds"
}

// GetMethodID returns the function id
func (t TransferFundsCall) GetMethodID() uint32 {
	return TransferFundsID
}

// GetMethodSelector returns the function selector
func (t TransferFundsCall) GetMethodSelector() [4]byte {
	return TransferFundsSelector
}

// EncodeWithSelector encodes transferFunds arguments to ABI bytes including function selector
func (t TransferFundsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TransferFundsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTransferFundsCall constructs a new TransferFundsCall
func NewTransferFundsCall(
	salt [32]byte,
	v *big.Int,
) *TransferFundsCall {
	return &TransferFundsCall{
		Salt: salt,
		V:    v,
	}
}

// TransferFundsReturn represents the output arguments for transferFunds function
type TransferFundsReturn struct {
	abi.EmptyTuple
}
