// Code generated by go-abi. DO NOT EDIT.

package testdata

import (
	"encoding/binary"
	"errors"
	"io"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// allowance(address,address)
	AllowanceSelector = [4]byte{0xdd, 0x62, 0xed, 0x3e}
	// approve(address,uint256)
	ApproveSelector = [4]byte{0x09, 0x5e, 0xa7, 0xb3}
	// balanceOf(address)
	BalanceOfSelector = [4]byte{0x70, 0xa0, 0x82, 0x31}
	// counter()
	CounterSelector = [4]byte{0x61, 0xbc, 0x22, 0x1a}
	// decimals()
	DecimalsSelector = [4]byte{0x31, 0x3c, 0xe5, 0x67}
	// name()
	NameSelector = [4]byte{0x06, 0xfd, 0xde, 0x03}
	// symbol()
	SymbolSelector = [4]byte{0x95, 0xd8, 0x9b, 0x41}
	// testTransferAndSend(address,uint256,uint256,uint256,bool,bool)
	TestTransferAndSendSelector = [4]byte{0x6b, 0xc7, 0xb7, 0xcd}
	// token()
	TokenSelector = [4]byte{0xfc, 0x0c, 0x54, 0x6a}
	// totalSupply()
	TotalSupplySelector = [4]byte{0x18, 0x16, 0x0d, 0xdd}
	// transfer(address,uint256)
	TransferSelector = [4]byte{0xa9, 0x05, 0x9c, 0xbb}
	// transferFrom(address,address,uint256)
	TransferFromSelector = [4]byte{0x23, 0xb8, 0x72, 0xdd}
	// transferWithRevert(address,uint256,bool,bool)
	TransferWithRevertSelector = [4]byte{0xd0, 0xfe, 0xdf, 0x55}
	// transfersWithTry(address,uint256,uint256)
	TransfersWithTrySelector = [4]byte{0x26, 0x8d, 0x07, 0x0a}
)

// Big endian integer versions of function selectors
const (
	AllowanceID           = 3714247998
	ApproveID             = 157198259
	BalanceOfID           = 1889567281
	CounterID             = 1639719450
	DecimalsID            = 826074471
	NameID                = 117300739
	SymbolID              = 2514000705
	TestTransferAndSendID = 1808250829
	TokenID               = 4228666474
	TotalSupplyID         = 404098525
	TransferID            = 2835717307
	TransferFromID        = 599290589
	TransferWithRevertID  = 3506364245
	TransfersWithTryID    = 646776586
)

var _ abi.Method = (*AllowanceCall)(nil)

const AllowanceCallStaticSize = 64

var _ abi.Tuple = (*AllowanceCall)(nil)

// AllowanceCall represents an ABI tuple
type AllowanceCall struct {
	Owner   common.Address
	Spender common.Address
}

// EncodedSize returns the total encoded size of AllowanceCall
func (t AllowanceCall) EncodedSize() int {
	dynamicSize := 0

	return AllowanceCallStaticSize + dynamicSize
}

// EncodeTo encodes AllowanceCall to ABI bytes in the provided buffer
func (value AllowanceCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AllowanceCallStaticSize // Start dynamic data after static section
	// Field Owner: address
	if _, err := abi.EncodeAddress(value.Owner, buf[0:]); err != nil {
		return 0, err
	}

	// Field Spender: address
	if _, err := abi.EncodeAddress(value.Spender, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes AllowanceCall to ABI bytes
func (value AllowanceCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AllowanceCall from ABI bytes in the provided buffer
func (t *AllowanceCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field Owner: address
	t.Owner, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Spender: address
	t.Spender, _, err = abi.DecodeAddress(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t AllowanceCall) GetMethodName() string {
	return "allowance"
}

// GetMethodID returns the function id
func (t AllowanceCall) GetMethodID() uint32 {
	return AllowanceID
}

// GetMethodSelector returns the function selector
func (t AllowanceCall) GetMethodSelector() [4]byte {
	return AllowanceSelector
}

// EncodeWithSelector encodes allowance arguments to ABI bytes including function selector
func (t AllowanceCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], AllowanceSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewAllowanceCall constructs a new AllowanceCall
func NewAllowanceCall(
	owner common.Address,
	spender common.Address,
) *AllowanceCall {
	return &AllowanceCall{
		Owner:   owner,
		Spender: spender,
	}
}

const AllowanceReturnStaticSize = 32

var _ abi.Tuple = (*AllowanceReturn)(nil)

// AllowanceReturn represents an ABI tuple
type AllowanceReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of AllowanceReturn
func (t AllowanceReturn) EncodedSize() int {
	dynamicSize := 0

	return AllowanceReturnStaticSize + dynamicSize
}

// EncodeTo encodes AllowanceReturn to ABI bytes in the provided buffer
func (value AllowanceReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AllowanceReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes AllowanceReturn to ABI bytes
func (value AllowanceReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AllowanceReturn from ABI bytes in the provided buffer
func (t *AllowanceReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*ApproveCall)(nil)

const ApproveCallStaticSize = 64

var _ abi.Tuple = (*ApproveCall)(nil)

// ApproveCall represents an ABI tuple
type ApproveCall struct {
	Spender common.Address
	Amount  *big.Int
}

// EncodedSize returns the total encoded size of ApproveCall
func (t ApproveCall) EncodedSize() int {
	dynamicSize := 0

	return ApproveCallStaticSize + dynamicSize
}

// EncodeTo encodes ApproveCall to ABI bytes in the provided buffer
func (value ApproveCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := ApproveCallStaticSize // Start dynamic data after static section
	// Field Spender: address
	if _, err := abi.EncodeAddress(value.Spender, buf[0:]); err != nil {
		return 0, err
	}

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes ApproveCall to ABI bytes
func (value ApproveCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ApproveCall from ABI bytes in the provided buffer
func (t *ApproveCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field Spender: address
	t.Spender, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t ApproveCall) GetMethodName() string {
	return "approve"
}

// GetMethodID returns the function id
func (t ApproveCall) GetMethodID() uint32 {
	return ApproveID
}

// GetMethodSelector returns the function selector
func (t ApproveCall) GetMethodSelector() [4]byte {
	return ApproveSelector
}

// EncodeWithSelector encodes approve arguments to ABI bytes including function selector
func (t ApproveCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ApproveSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewApproveCall constructs a new ApproveCall
func NewApproveCall(
	spender common.Address,
	amount *big.Int,
) *ApproveCall {
	return &ApproveCall{
		Spender: spender,
		Amount:  amount,
	}
}

const ApproveReturnStaticSize = 32

var _ abi.Tuple = (*ApproveReturn)(nil)

// ApproveReturn represents an ABI tuple
type ApproveReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of ApproveReturn
func (t ApproveReturn) EncodedSize() int {
	dynamicSize := 0

	return ApproveReturnStaticSize + dynamicSize
}

// EncodeTo encodes ApproveReturn to ABI bytes in the provided buffer
func (value ApproveReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := ApproveReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes ApproveReturn to ABI bytes
func (value ApproveReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ApproveReturn from ABI bytes in the provided buffer
func (t *ApproveReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*BalanceOfCall)(nil)

const BalanceOfCallStaticSize = 32

var _ abi.Tuple = (*BalanceOfCall)(nil)

// BalanceOfCall represents an ABI tuple
type BalanceOfCall struct {
	Owner common.Address
}

// EncodedSize returns the total encoded size of BalanceOfCall
func (t BalanceOfCall) EncodedSize() int {
	dynamicSize := 0

	return BalanceOfCallStaticSize + dynamicSize
}

// EncodeTo encodes BalanceOfCall to ABI bytes in the provided buffer
func (value BalanceOfCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := BalanceOfCallStaticSize // Start dynamic data after static section
	// Field Owner: address
	if _, err := abi.EncodeAddress(value.Owner, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes BalanceOfCall to ABI bytes
func (value BalanceOfCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes BalanceOfCall from ABI bytes in the provided buffer
func (t *BalanceOfCall) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Owner: address
	t.Owner, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t BalanceOfCall) GetMethodName() string {
	return "balanceOf"
}

// GetMethodID returns the function id
func (t BalanceOfCall) GetMethodID() uint32 {
	return BalanceOfID
}

// GetMethodSelector returns the function selector
func (t BalanceOfCall) GetMethodSelector() [4]byte {
	return BalanceOfSelector
}

// EncodeWithSelector encodes balanceOf arguments to ABI bytes including function selector
func (t BalanceOfCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], BalanceOfSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewBalanceOfCall constructs a new BalanceOfCall
func NewBalanceOfCall(
	owner common.Address,
) *BalanceOfCall {
	return &BalanceOfCall{
		Owner: owner,
	}
}

const BalanceOfReturnStaticSize = 32

var _ abi.Tuple = (*BalanceOfReturn)(nil)

// BalanceOfReturn represents an ABI tuple
type BalanceOfReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of BalanceOfReturn
func (t BalanceOfReturn) EncodedSize() int {
	dynamicSize := 0

	return BalanceOfReturnStaticSize + dynamicSize
}

// EncodeTo encodes BalanceOfReturn to ABI bytes in the provided buffer
func (value BalanceOfReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := BalanceOfReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes BalanceOfReturn to ABI bytes
func (value BalanceOfReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes BalanceOfReturn from ABI bytes in the provided buffer
func (t *BalanceOfReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*CounterCall)(nil)

// CounterCall represents the input arguments for counter function
type CounterCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t CounterCall) GetMethodName() string {
	return "counter"
}

// GetMethodID returns the function id
func (t CounterCall) GetMethodID() uint32 {
	return CounterID
}

// GetMethodSelector returns the function selector
func (t CounterCall) GetMethodSelector() [4]byte {
	return CounterSelector
}

// EncodeWithSelector encodes counter arguments to ABI bytes including function selector
func (t CounterCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], CounterSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewCounterCall constructs a new CounterCall
func NewCounterCall() *CounterCall {
	return &CounterCall{}
}

const CounterReturnStaticSize = 32

var _ abi.Tuple = (*CounterReturn)(nil)

// CounterReturn represents an ABI tuple
type CounterReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of CounterReturn
func (t CounterReturn) EncodedSize() int {
	dynamicSize := 0

	return CounterReturnStaticSize + dynamicSize
}

// EncodeTo encodes CounterReturn to ABI bytes in the provided buffer
func (value CounterReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := CounterReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes CounterReturn to ABI bytes
func (value CounterReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes CounterReturn from ABI bytes in the provided buffer
func (t *CounterReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*DecimalsCall)(nil)

// DecimalsCall represents the input arguments for decimals function
type DecimalsCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t DecimalsCall) GetMethodName() string {
	return "decimals"
}

// GetMethodID returns the function id
func (t DecimalsCall) GetMethodID() uint32 {
	return DecimalsID
}

// GetMethodSelector returns the function selector
func (t DecimalsCall) GetMethodSelector() [4]byte {
	return DecimalsSelector
}

// EncodeWithSelector encodes decimals arguments to ABI bytes including function selector
func (t DecimalsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DecimalsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewDecimalsCall constructs a new DecimalsCall
func NewDecimalsCall() *DecimalsCall {
	return &DecimalsCall{}
}

const DecimalsReturnStaticSize = 32

var _ abi.Tuple = (*DecimalsReturn)(nil)

// DecimalsReturn represents an ABI tuple
type DecimalsReturn struct {
	Field1 uint8
}

// EncodedSize returns the total encoded size of DecimalsReturn
func (t DecimalsReturn) EncodedSize() int {
	dynamicSize := 0

	return DecimalsReturnStaticSize + dynamicSize
}

// EncodeTo encodes DecimalsReturn to ABI bytes in the provided buffer
func (value DecimalsReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := DecimalsReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint8
	if _, err := abi.EncodeUint8(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes DecimalsReturn to ABI bytes
func (value DecimalsReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DecimalsReturn from ABI bytes in the provided buffer
func (t *DecimalsReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint8
	t.Field1, _, err = abi.DecodeUint8(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*NameCall)(nil)

// NameCall represents the input arguments for name function
type NameCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t NameCall) GetMethodName() string {
	return "name"
}

// GetMethodID returns the function id
func (t NameCall) GetMethodID() uint32 {
	return NameID
}

// GetMethodSelector returns the function selector
func (t NameCall) GetMethodSelector() [4]byte {
	return NameSelector
}

// EncodeWithSelector encodes name arguments to ABI bytes including function selector
func (t NameCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], NameSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewNameCall constructs a new NameCall
func NewNameCall() *NameCall {
	return &NameCall{}
}

const NameReturnStaticSize = 32

var _ abi.Tuple = (*NameReturn)(nil)

// NameReturn represents an ABI tuple
type NameReturn struct {
	Field1 string
}

// EncodedSize returns the total encoded size of NameReturn
func (t NameReturn) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Field1)

	return NameReturnStaticSize + dynamicSize
}

// EncodeTo encodes NameReturn to ABI bytes in the provided buffer
func (value NameReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := NameReturnStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Field1: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Field1, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes NameReturn to ABI bytes
func (value NameReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes NameReturn from ABI bytes in the provided buffer
func (t *NameReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 32
	// Decode dynamic field Field1
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Field1")
		}
		t.Field1, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*SymbolCall)(nil)

// SymbolCall represents the input arguments for symbol function
type SymbolCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t SymbolCall) GetMethodName() string {
	return "symbol"
}

// GetMethodID returns the function id
func (t SymbolCall) GetMethodID() uint32 {
	return SymbolID
}

// GetMethodSelector returns the function selector
func (t SymbolCall) GetMethodSelector() [4]byte {
	return SymbolSelector
}

// EncodeWithSelector encodes symbol arguments to ABI bytes including function selector
func (t SymbolCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], SymbolSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewSymbolCall constructs a new SymbolCall
func NewSymbolCall() *SymbolCall {
	return &SymbolCall{}
}

const SymbolReturnStaticSize = 32

var _ abi.Tuple = (*SymbolReturn)(nil)

// SymbolReturn represents an ABI tuple
type SymbolReturn struct {
	Field1 string
}

// EncodedSize returns the total encoded size of SymbolReturn
func (t SymbolReturn) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Field1)

	return SymbolReturnStaticSize + dynamicSize
}

// EncodeTo encodes SymbolReturn to ABI bytes in the provided buffer
func (value SymbolReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := SymbolReturnStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Field1: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Field1, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes SymbolReturn to ABI bytes
func (value SymbolReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes SymbolReturn from ABI bytes in the provided buffer
func (t *SymbolReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 32
	// Decode dynamic field Field1
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Field1")
		}
		t.Field1, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TestTransferAndSendCall)(nil)

const TestTransferAndSendCallStaticSize = 192

var _ abi.Tuple = (*TestTransferAndSendCall)(nil)

// TestTransferAndSendCall represents an ABI tuple
type TestTransferAndSendCall struct {
	Source               common.Address
	Amount_to_transfer   *big.Int
	Amount_to_send       *big.Int
	Amount_to_send_after *big.Int
	Before               bool
	After                bool
}

// EncodedSize returns the total encoded size of TestTransferAndSendCall
func (t TestTransferAndSendCall) EncodedSize() int {
	dynamicSize := 0

	return TestTransferAndSendCallStaticSize + dynamicSize
}

// EncodeTo encodes TestTransferAndSendCall to ABI bytes in the provided buffer
func (value TestTransferAndSendCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestTransferAndSendCallStaticSize // Start dynamic data after static section
	// Field Source: address
	if _, err := abi.EncodeAddress(value.Source, buf[0:]); err != nil {
		return 0, err
	}

	// Field Amount_to_transfer: uint256
	if _, err := abi.EncodeUint256(value.Amount_to_transfer, buf[32:]); err != nil {
		return 0, err
	}

	// Field Amount_to_send: uint256
	if _, err := abi.EncodeUint256(value.Amount_to_send, buf[64:]); err != nil {
		return 0, err
	}

	// Field Amount_to_send_after: uint256
	if _, err := abi.EncodeUint256(value.Amount_to_send_after, buf[96:]); err != nil {
		return 0, err
	}

	// Field Before: bool
	if _, err := abi.EncodeBool(value.Before, buf[128:]); err != nil {
		return 0, err
	}

	// Field After: bool
	if _, err := abi.EncodeBool(value.After, buf[160:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestTransferAndSendCall to ABI bytes
func (value TestTransferAndSendCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestTransferAndSendCall from ABI bytes in the provided buffer
func (t *TestTransferAndSendCall) Decode(data []byte) (int, error) {
	if len(data) < 192 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 192
	// Decode static field Source: address
	t.Source, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount_to_transfer: uint256
	t.Amount_to_transfer, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount_to_send: uint256
	t.Amount_to_send, _, err = abi.DecodeUint256(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount_to_send_after: uint256
	t.Amount_to_send_after, _, err = abi.DecodeUint256(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode static field Before: bool
	t.Before, _, err = abi.DecodeBool(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode static field After: bool
	t.After, _, err = abi.DecodeBool(data[160:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestTransferAndSendCall) GetMethodName() string {
	return "testTransferAndSend"
}

// GetMethodID returns the function id
func (t TestTransferAndSendCall) GetMethodID() uint32 {
	return TestTransferAndSendID
}

// GetMethodSelector returns the function selector
func (t TestTransferAndSendCall) GetMethodSelector() [4]byte {
	return TestTransferAndSendSelector
}

// EncodeWithSelector encodes testTransferAndSend arguments to ABI bytes including function selector
func (t TestTransferAndSendCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestTransferAndSendSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTestTransferAndSendCall constructs a new TestTransferAndSendCall
func NewTestTransferAndSendCall(
	source common.Address,
	amount_to_transfer *big.Int,
	amount_to_send *big.Int,
	amount_to_send_after *big.Int,
	before bool,
	after bool,
) *TestTransferAndSendCall {
	return &TestTransferAndSendCall{
		Source:               source,
		Amount_to_transfer:   amount_to_transfer,
		Amount_to_send:       amount_to_send,
		Amount_to_send_after: amount_to_send_after,
		Before:               before,
		After:                after,
	}
}

const TestTransferAndSendReturnStaticSize = 32

var _ abi.Tuple = (*TestTransferAndSendReturn)(nil)

// TestTransferAndSendReturn represents an ABI tuple
type TestTransferAndSendReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of TestTransferAndSendReturn
func (t TestTransferAndSendReturn) EncodedSize() int {
	dynamicSize := 0

	return TestTransferAndSendReturnStaticSize + dynamicSize
}

// EncodeTo encodes TestTransferAndSendReturn to ABI bytes in the provided buffer
func (value TestTransferAndSendReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestTransferAndSendReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestTransferAndSendReturn to ABI bytes
func (value TestTransferAndSendReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestTransferAndSendReturn from ABI bytes in the provided buffer
func (t *TestTransferAndSendReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TokenCall)(nil)

// TokenCall represents the input arguments for token function
type TokenCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t TokenCall) GetMethodName() string {
	return "token"
}

// GetMethodID returns the function id
func (t TokenCall) GetMethodID() uint32 {
	return TokenID
}

// GetMethodSelector returns the function selector
func (t TokenCall) GetMethodSelector() [4]byte {
	return TokenSelector
}

// EncodeWithSelector encodes token arguments to ABI bytes including function selector
func (t TokenCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TokenSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTokenCall constructs a new TokenCall
func NewTokenCall() *TokenCall {
	return &TokenCall{}
}

const TokenReturnStaticSize = 32

var _ abi.Tuple = (*TokenReturn)(nil)

// TokenReturn represents an ABI tuple
type TokenReturn struct {
	Field1 common.Address
}

// EncodedSize returns the total encoded size of TokenReturn
func (t TokenReturn) EncodedSize() int {
	dynamicSize := 0

	return TokenReturnStaticSize + dynamicSize
}

// EncodeTo encodes TokenReturn to ABI bytes in the provided buffer
func (value TokenReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TokenReturnStaticSize // Start dynamic data after static section
	// Field Field1: address
	if _, err := abi.EncodeAddress(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TokenReturn to ABI bytes
func (value TokenReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TokenReturn from ABI bytes in the provided buffer
func (t *TokenReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: address
	t.Field1, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TotalSupplyCall)(nil)

// TotalSupplyCall represents the input arguments for totalSupply function
type TotalSupplyCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t TotalSupplyCall) GetMethodName() string {
	return "totalSupply"
}

// GetMethodID returns the function id
func (t TotalSupplyCall) GetMethodID() uint32 {
	return TotalSupplyID
}

// GetMethodSelector returns the function selector
func (t TotalSupplyCall) GetMethodSelector() [4]byte {
	return TotalSupplySelector
}

// EncodeWithSelector encodes totalSupply arguments to ABI bytes including function selector
func (t TotalSupplyCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TotalSupplySelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTotalSupplyCall constructs a new TotalSupplyCall
func NewTotalSupplyCall() *TotalSupplyCall {
	return &TotalSupplyCall{}
}

const TotalSupplyReturnStaticSize = 32

var _ abi.Tuple = (*TotalSupplyReturn)(nil)

// TotalSupplyReturn represents an ABI tuple
type TotalSupplyReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of TotalSupplyReturn
func (t TotalSupplyReturn) EncodedSize() int {
	dynamicSize := 0

	return TotalSupplyReturnStaticSize + dynamicSize
}

// EncodeTo encodes TotalSupplyReturn to ABI bytes in the provided buffer
func (value TotalSupplyReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TotalSupplyReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TotalSupplyReturn to ABI bytes
func (value TotalSupplyReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TotalSupplyReturn from ABI bytes in the provided buffer
func (t *TotalSupplyReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TransferCall)(nil)

const TransferCallStaticSize = 64

var _ abi.Tuple = (*TransferCall)(nil)

// TransferCall represents an ABI tuple
type TransferCall struct {
	To     common.Address
	Amount *big.Int
}

// EncodedSize returns the total encoded size of TransferCall
func (t TransferCall) EncodedSize() int {
	dynamicSize := 0

	return TransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TransferCall to ABI bytes in the provided buffer
func (value TransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransferCallStaticSize // Start dynamic data after static section
	// Field To: address
	if _, err := abi.EncodeAddress(value.To, buf[0:]); err != nil {
		return 0, err
	}

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransferCall to ABI bytes
func (value TransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferCall from ABI bytes in the provided buffer
func (t *TransferCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field To: address
	t.To, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TransferCall) GetMethodName() string {
	return "transfer"
}

// GetMethodID returns the function id
func (t TransferCall) GetMethodID() uint32 {
	return TransferID
}

// GetMethodSelector returns the function selector
func (t TransferCall) GetMethodSelector() [4]byte {
	return TransferSelector
}

// EncodeWithSelector encodes transfer arguments to ABI bytes including function selector
func (t TransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTransferCall constructs a new TransferCall
func NewTransferCall(
	to common.Address,
	amount *big.Int,
) *TransferCall {
	return &TransferCall{
		To:     to,
		Amount: amount,
	}
}

const TransferReturnStaticSize = 32

var _ abi.Tuple = (*TransferReturn)(nil)

// TransferReturn represents an ABI tuple
type TransferReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of TransferReturn
func (t TransferReturn) EncodedSize() int {
	dynamicSize := 0

	return TransferReturnStaticSize + dynamicSize
}

// EncodeTo encodes TransferReturn to ABI bytes in the provided buffer
func (value TransferReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransferReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransferReturn to ABI bytes
func (value TransferReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferReturn from ABI bytes in the provided buffer
func (t *TransferReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TransferFromCall)(nil)

const TransferFromCallStaticSize = 96

var _ abi.Tuple = (*TransferFromCall)(nil)

// TransferFromCall represents an ABI tuple
type TransferFromCall struct {
	From   common.Address
	To     common.Address
	Amount *big.Int
}

// EncodedSize returns the total encoded size of TransferFromCall
func (t TransferFromCall) EncodedSize() int {
	dynamicSize := 0

	return TransferFromCallStaticSize + dynamicSize
}

// EncodeTo encodes TransferFromCall to ABI bytes in the provided buffer
func (value TransferFromCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransferFromCallStaticSize // Start dynamic data after static section
	// Field From: address
	if _, err := abi.EncodeAddress(value.From, buf[0:]); err != nil {
		return 0, err
	}

	// Field To: address
	if _, err := abi.EncodeAddress(value.To, buf[32:]); err != nil {
		return 0, err
	}

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[64:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransferFromCall to ABI bytes
func (value TransferFromCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferFromCall from ABI bytes in the provided buffer
func (t *TransferFromCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 96
	// Decode static field From: address
	t.From, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field To: address
	t.To, _, err = abi.DecodeAddress(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[64:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TransferFromCall) GetMethodName() string {
	return "transferFrom"
}

// GetMethodID returns the function id
func (t TransferFromCall) GetMethodID() uint32 {
	return TransferFromID
}

// GetMethodSelector returns the function selector
func (t TransferFromCall) GetMethodSelector() [4]byte {
	return TransferFromSelector
}

// EncodeWithSelector encodes transferFrom arguments to ABI bytes including function selector
func (t TransferFromCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TransferFromSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTransferFromCall constructs a new TransferFromCall
func NewTransferFromCall(
	from common.Address,
	to common.Address,
	amount *big.Int,
) *TransferFromCall {
	return &TransferFromCall{
		From:   from,
		To:     to,
		Amount: amount,
	}
}

const TransferFromReturnStaticSize = 32

var _ abi.Tuple = (*TransferFromReturn)(nil)

// TransferFromReturn represents an ABI tuple
type TransferFromReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of TransferFromReturn
func (t TransferFromReturn) EncodedSize() int {
	dynamicSize := 0

	return TransferFromReturnStaticSize + dynamicSize
}

// EncodeTo encodes TransferFromReturn to ABI bytes in the provided buffer
func (value TransferFromReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransferFromReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransferFromReturn to ABI bytes
func (value TransferFromReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferFromReturn from ABI bytes in the provided buffer
func (t *TransferFromReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TransferWithRevertCall)(nil)

const TransferWithRevertCallStaticSize = 128

var _ abi.Tuple = (*TransferWithRevertCall)(nil)

// TransferWithRevertCall represents an ABI tuple
type TransferWithRevertCall struct {
	To     common.Address
	Amount *big.Int
	Before bool
	Aft    bool
}

// EncodedSize returns the total encoded size of TransferWithRevertCall
func (t TransferWithRevertCall) EncodedSize() int {
	dynamicSize := 0

	return TransferWithRevertCallStaticSize + dynamicSize
}

// EncodeTo encodes TransferWithRevertCall to ABI bytes in the provided buffer
func (value TransferWithRevertCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransferWithRevertCallStaticSize // Start dynamic data after static section
	// Field To: address
	if _, err := abi.EncodeAddress(value.To, buf[0:]); err != nil {
		return 0, err
	}

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[32:]); err != nil {
		return 0, err
	}

	// Field Before: bool
	if _, err := abi.EncodeBool(value.Before, buf[64:]); err != nil {
		return 0, err
	}

	// Field Aft: bool
	if _, err := abi.EncodeBool(value.Aft, buf[96:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransferWithRevertCall to ABI bytes
func (value TransferWithRevertCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferWithRevertCall from ABI bytes in the provided buffer
func (t *TransferWithRevertCall) Decode(data []byte) (int, error) {
	if len(data) < 128 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 128
	// Decode static field To: address
	t.To, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Before: bool
	t.Before, _, err = abi.DecodeBool(data[64:])
	if err != nil {
		return 0, err
	}
	// Decode static field Aft: bool
	t.Aft, _, err = abi.DecodeBool(data[96:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TransferWithRevertCall) GetMethodName() string {
	return "transferWithRevert"
}

// GetMethodID returns the function id
func (t TransferWithRevertCall) GetMethodID() uint32 {
	return TransferWithRevertID
}

// GetMethodSelector returns the function selector
func (t TransferWithRevertCall) GetMethodSelector() [4]byte {
	return TransferWithRevertSelector
}

// EncodeWithSelector encodes transferWithRevert arguments to ABI bytes including function selector
func (t TransferWithRevertCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TransferWithRevertSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTransferWithRevertCall constructs a new TransferWithRevertCall
func NewTransferWithRevertCall(
	to common.Address,
	amount *big.Int,
	before bool,
	aft bool,
) *TransferWithRevertCall {
	return &TransferWithRevertCall{
		To:     to,
		Amount: amount,
		Before: before,
		Aft:    aft,
	}
}

const TransferWithRevertReturnStaticSize = 32

var _ abi.Tuple = (*TransferWithRevertReturn)(nil)

// TransferWithRevertReturn represents an ABI tuple
type TransferWithRevertReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of TransferWithRevertReturn
func (t TransferWithRevertReturn) EncodedSize() int {
	dynamicSize := 0

	return TransferWithRevertReturnStaticSize + dynamicSize
}

// EncodeTo encodes TransferWithRevertReturn to ABI bytes in the provided buffer
func (value TransferWithRevertReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransferWithRevertReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransferWithRevertReturn to ABI bytes
func (value TransferWithRevertReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferWithRevertReturn from ABI bytes in the provided buffer
func (t *TransferWithRevertReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TransfersWithTryCall)(nil)

const TransfersWithTryCallStaticSize = 96

var _ abi.Tuple = (*TransfersWithTryCall)(nil)

// TransfersWithTryCall represents an ABI tuple
type TransfersWithTryCall struct {
	Receiver           common.Address
	Amount_to_transfer *big.Int
	Amount_to_fail     *big.Int
}

// EncodedSize returns the total encoded size of TransfersWithTryCall
func (t TransfersWithTryCall) EncodedSize() int {
	dynamicSize := 0

	return TransfersWithTryCallStaticSize + dynamicSize
}

// EncodeTo encodes TransfersWithTryCall to ABI bytes in the provided buffer
func (value TransfersWithTryCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TransfersWithTryCallStaticSize // Start dynamic data after static section
	// Field Receiver: address
	if _, err := abi.EncodeAddress(value.Receiver, buf[0:]); err != nil {
		return 0, err
	}

	// Field Amount_to_transfer: uint256
	if _, err := abi.EncodeUint256(value.Amount_to_transfer, buf[32:]); err != nil {
		return 0, err
	}

	// Field Amount_to_fail: uint256
	if _, err := abi.EncodeUint256(value.Amount_to_fail, buf[64:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TransfersWithTryCall to ABI bytes
func (value TransfersWithTryCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransfersWithTryCall from ABI bytes in the provided buffer
func (t *TransfersWithTryCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 96
	// Decode static field Receiver: address
	t.Receiver, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount_to_transfer: uint256
	t.Amount_to_transfer, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field Amount_to_fail: uint256
	t.Amount_to_fail, _, err = abi.DecodeUint256(data[64:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TransfersWithTryCall) GetMethodName() string {
	return "transfersWithTry"
}

// GetMethodID returns the function id
func (t TransfersWithTryCall) GetMethodID() uint32 {
	return TransfersWithTryID
}

// GetMethodSelector returns the function selector
func (t TransfersWithTryCall) GetMethodSelector() [4]byte {
	return TransfersWithTrySelector
}

// EncodeWithSelector encodes transfersWithTry arguments to ABI bytes including function selector
func (t TransfersWithTryCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TransfersWithTrySelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTransfersWithTryCall constructs a new TransfersWithTryCall
func NewTransfersWithTryCall(
	receiver common.Address,
	amount_to_transfer *big.Int,
	amount_to_fail *big.Int,
) *TransfersWithTryCall {
	return &TransfersWithTryCall{
		Receiver:           receiver,
		Amount_to_transfer: amount_to_transfer,
		Amount_to_fail:     amount_to_fail,
	}
}

// TransfersWithTryReturn represents the output arguments for transfersWithTry function
type TransfersWithTryReturn struct {
	abi.EmptyTuple
}
