// Code generated by go-abi. DO NOT EDIT.

package stakingcaller2

import (
	"encoding/binary"
	"errors"
	"io"
	"math/big"

	"github.com/cosmos/evm/precompiles/staking"
	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// counter()
	CounterSelector = [4]byte{0x61, 0xbc, 0x22, 0x1a}
	// delegation(address,string)
	DelegationSelector = [4]byte{0x24, 0x17, 0x74, 0xe6}
	// testCreateValidatorWithTransfer((string,string,string,string,string),(uint256,uint256,uint256),uint256,address,string,bool,bool)
	TestCreateValidatorWithTransferSelector = [4]byte{0xb9, 0xa6, 0xbb, 0xca}
	// testDelegateWithCounterAndTransfer(string,bool,bool)
	TestDelegateWithCounterAndTransferSelector = [4]byte{0xc5, 0xb7, 0x5f, 0x01}
	// testDelegateWithTransfer(address,address,string,bool,bool)
	TestDelegateWithTransferSelector = [4]byte{0x66, 0xda, 0xfc, 0x7a}
)

// Big endian integer versions of function selectors
const (
	CounterID                            = 1639719450
	DelegationID                         = 605517030
	TestCreateValidatorWithTransferID    = 3114712010
	TestDelegateWithCounterAndTransferID = 3317128961
	TestDelegateWithTransferID           = 1725627514
)

var _ abi.Method = (*CounterCall)(nil)

// CounterCall represents the input arguments for counter function
type CounterCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t CounterCall) GetMethodName() string {
	return "counter"
}

// GetMethodID returns the function id
func (t CounterCall) GetMethodID() uint32 {
	return CounterID
}

// GetMethodSelector returns the function selector
func (t CounterCall) GetMethodSelector() [4]byte {
	return CounterSelector
}

// EncodeWithSelector encodes counter arguments to ABI bytes including function selector
func (t CounterCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], CounterSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewCounterCall constructs a new CounterCall
func NewCounterCall() *CounterCall {
	return &CounterCall{}
}

const CounterReturnStaticSize = 32

var _ abi.Tuple = (*CounterReturn)(nil)

// CounterReturn represents an ABI tuple
type CounterReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of CounterReturn
func (t CounterReturn) EncodedSize() int {
	dynamicSize := 0

	return CounterReturnStaticSize + dynamicSize
}

// EncodeTo encodes CounterReturn to ABI bytes in the provided buffer
func (value CounterReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := CounterReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes CounterReturn to ABI bytes
func (value CounterReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes CounterReturn from ABI bytes in the provided buffer
func (t *CounterReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*DelegationCall)(nil)

const DelegationCallStaticSize = 64

var _ abi.Tuple = (*DelegationCall)(nil)

// DelegationCall represents an ABI tuple
type DelegationCall struct {
	Field1 common.Address
	Field2 string
}

// EncodedSize returns the total encoded size of DelegationCall
func (t DelegationCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Field2)

	return DelegationCallStaticSize + dynamicSize
}

// EncodeTo encodes DelegationCall to ABI bytes in the provided buffer
func (value DelegationCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := DelegationCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Field1: address
	if _, err := abi.EncodeAddress(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	// Field Field2: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Field2, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes DelegationCall to ABI bytes
func (value DelegationCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegationCall from ABI bytes in the provided buffer
func (t *DelegationCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 64
	// Decode static field Field1: address
	t.Field1, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Field2
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Field2")
		}
		t.Field2, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t DelegationCall) GetMethodName() string {
	return "delegation"
}

// GetMethodID returns the function id
func (t DelegationCall) GetMethodID() uint32 {
	return DelegationID
}

// GetMethodSelector returns the function selector
func (t DelegationCall) GetMethodSelector() [4]byte {
	return DelegationSelector
}

// EncodeWithSelector encodes delegation arguments to ABI bytes including function selector
func (t DelegationCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DelegationSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewDelegationCall constructs a new DelegationCall
func NewDelegationCall(
	field1 common.Address,
	field2 string,
) *DelegationCall {
	return &DelegationCall{
		Field1: field1,
		Field2: field2,
	}
}

const DelegationReturnStaticSize = 32

var _ abi.Tuple = (*DelegationReturn)(nil)

// DelegationReturn represents an ABI tuple
type DelegationReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of DelegationReturn
func (t DelegationReturn) EncodedSize() int {
	dynamicSize := 0

	return DelegationReturnStaticSize + dynamicSize
}

// EncodeTo encodes DelegationReturn to ABI bytes in the provided buffer
func (value DelegationReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := DelegationReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes DelegationReturn to ABI bytes
func (value DelegationReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegationReturn from ABI bytes in the provided buffer
func (t *DelegationReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TestCreateValidatorWithTransferCall)(nil)

const TestCreateValidatorWithTransferCallStaticSize = 288

var _ abi.Tuple = (*TestCreateValidatorWithTransferCall)(nil)

// TestCreateValidatorWithTransferCall represents an ABI tuple
type TestCreateValidatorWithTransferCall struct {
	Descr      staking.Description
	CommRates  staking.CommissionRates
	MinSelfDel *big.Int
	Validator  common.Address
	Pubkey     string
	Before     bool
	After      bool
}

// EncodedSize returns the total encoded size of TestCreateValidatorWithTransferCall
func (t TestCreateValidatorWithTransferCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += t.Descr.EncodedSize()
	dynamicSize += abi.SizeString(t.Pubkey)

	return TestCreateValidatorWithTransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TestCreateValidatorWithTransferCall to ABI bytes in the provided buffer
func (value TestCreateValidatorWithTransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestCreateValidatorWithTransferCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Descr: (string,string,string,string,string)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Descr.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field CommRates: (uint256,uint256,uint256)
	if _, err := value.CommRates.EncodeTo(buf[32:]); err != nil {
		return 0, err
	}

	// Field MinSelfDel: uint256
	if _, err := abi.EncodeUint256(value.MinSelfDel, buf[128:]); err != nil {
		return 0, err
	}

	// Field Validator: address
	if _, err := abi.EncodeAddress(value.Validator, buf[160:]); err != nil {
		return 0, err
	}

	// Field Pubkey: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[192+24:192+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Pubkey, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Before: bool
	if _, err := abi.EncodeBool(value.Before, buf[224:]); err != nil {
		return 0, err
	}

	// Field After: bool
	if _, err := abi.EncodeBool(value.After, buf[256:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestCreateValidatorWithTransferCall to ABI bytes
func (value TestCreateValidatorWithTransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestCreateValidatorWithTransferCall from ABI bytes in the provided buffer
func (t *TestCreateValidatorWithTransferCall) Decode(data []byte) (int, error) {
	if len(data) < 288 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 288
	// Decode dynamic field Descr
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Descr")
		}
		n, err = t.Descr.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field CommRates: (uint256,uint256,uint256)
	_, err = t.CommRates.Decode(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field MinSelfDel: uint256
	t.MinSelfDel, _, err = abi.DecodeUint256(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode static field Validator: address
	t.Validator, _, err = abi.DecodeAddress(data[160:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Pubkey
	{
		offset := int(binary.BigEndian.Uint64(data[192+24 : 192+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Pubkey")
		}
		t.Pubkey, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Before: bool
	t.Before, _, err = abi.DecodeBool(data[224:])
	if err != nil {
		return 0, err
	}
	// Decode static field After: bool
	t.After, _, err = abi.DecodeBool(data[256:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestCreateValidatorWithTransferCall) GetMethodName() string {
	return "testCreateValidatorWithTransfer"
}

// GetMethodID returns the function id
func (t TestCreateValidatorWithTransferCall) GetMethodID() uint32 {
	return TestCreateValidatorWithTransferID
}

// GetMethodSelector returns the function selector
func (t TestCreateValidatorWithTransferCall) GetMethodSelector() [4]byte {
	return TestCreateValidatorWithTransferSelector
}

// EncodeWithSelector encodes testCreateValidatorWithTransfer arguments to ABI bytes including function selector
func (t TestCreateValidatorWithTransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestCreateValidatorWithTransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTestCreateValidatorWithTransferCall constructs a new TestCreateValidatorWithTransferCall
func NewTestCreateValidatorWithTransferCall(
	descr staking.Description,
	commRates staking.CommissionRates,
	minSelfDel *big.Int,
	validator common.Address,
	pubkey string,
	before bool,
	after bool,
) *TestCreateValidatorWithTransferCall {
	return &TestCreateValidatorWithTransferCall{
		Descr:      descr,
		CommRates:  commRates,
		MinSelfDel: minSelfDel,
		Validator:  validator,
		Pubkey:     pubkey,
		Before:     before,
		After:      after,
	}
}

// TestCreateValidatorWithTransferReturn represents the output arguments for testCreateValidatorWithTransfer function
type TestCreateValidatorWithTransferReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*TestDelegateWithCounterAndTransferCall)(nil)

const TestDelegateWithCounterAndTransferCallStaticSize = 96

var _ abi.Tuple = (*TestDelegateWithCounterAndTransferCall)(nil)

// TestDelegateWithCounterAndTransferCall represents an ABI tuple
type TestDelegateWithCounterAndTransferCall struct {
	ValidatorAddr string
	Before        bool
	After         bool
}

// EncodedSize returns the total encoded size of TestDelegateWithCounterAndTransferCall
func (t TestDelegateWithCounterAndTransferCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddr)

	return TestDelegateWithCounterAndTransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TestDelegateWithCounterAndTransferCall to ABI bytes in the provided buffer
func (value TestDelegateWithCounterAndTransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestDelegateWithCounterAndTransferCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field ValidatorAddr: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddr, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Before: bool
	if _, err := abi.EncodeBool(value.Before, buf[32:]); err != nil {
		return 0, err
	}

	// Field After: bool
	if _, err := abi.EncodeBool(value.After, buf[64:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestDelegateWithCounterAndTransferCall to ABI bytes
func (value TestDelegateWithCounterAndTransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestDelegateWithCounterAndTransferCall from ABI bytes in the provided buffer
func (t *TestDelegateWithCounterAndTransferCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 96
	// Decode dynamic field ValidatorAddr
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field ValidatorAddr")
		}
		t.ValidatorAddr, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Before: bool
	t.Before, _, err = abi.DecodeBool(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode static field After: bool
	t.After, _, err = abi.DecodeBool(data[64:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestDelegateWithCounterAndTransferCall) GetMethodName() string {
	return "testDelegateWithCounterAndTransfer"
}

// GetMethodID returns the function id
func (t TestDelegateWithCounterAndTransferCall) GetMethodID() uint32 {
	return TestDelegateWithCounterAndTransferID
}

// GetMethodSelector returns the function selector
func (t TestDelegateWithCounterAndTransferCall) GetMethodSelector() [4]byte {
	return TestDelegateWithCounterAndTransferSelector
}

// EncodeWithSelector encodes testDelegateWithCounterAndTransfer arguments to ABI bytes including function selector
func (t TestDelegateWithCounterAndTransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestDelegateWithCounterAndTransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTestDelegateWithCounterAndTransferCall constructs a new TestDelegateWithCounterAndTransferCall
func NewTestDelegateWithCounterAndTransferCall(
	validatorAddr string,
	before bool,
	after bool,
) *TestDelegateWithCounterAndTransferCall {
	return &TestDelegateWithCounterAndTransferCall{
		ValidatorAddr: validatorAddr,
		Before:        before,
		After:         after,
	}
}

// TestDelegateWithCounterAndTransferReturn represents the output arguments for testDelegateWithCounterAndTransfer function
type TestDelegateWithCounterAndTransferReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*TestDelegateWithTransferCall)(nil)

const TestDelegateWithTransferCallStaticSize = 160

var _ abi.Tuple = (*TestDelegateWithTransferCall)(nil)

// TestDelegateWithTransferCall represents an ABI tuple
type TestDelegateWithTransferCall struct {
	Dest          common.Address
	Delegator     common.Address
	ValidatorAddr string
	Before        bool
	After         bool
}

// EncodedSize returns the total encoded size of TestDelegateWithTransferCall
func (t TestDelegateWithTransferCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddr)

	return TestDelegateWithTransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TestDelegateWithTransferCall to ABI bytes in the provided buffer
func (value TestDelegateWithTransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestDelegateWithTransferCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Dest: address
	if _, err := abi.EncodeAddress(value.Dest, buf[0:]); err != nil {
		return 0, err
	}

	// Field Delegator: address
	if _, err := abi.EncodeAddress(value.Delegator, buf[32:]); err != nil {
		return 0, err
	}

	// Field ValidatorAddr: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddr, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Before: bool
	if _, err := abi.EncodeBool(value.Before, buf[96:]); err != nil {
		return 0, err
	}

	// Field After: bool
	if _, err := abi.EncodeBool(value.After, buf[128:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestDelegateWithTransferCall to ABI bytes
func (value TestDelegateWithTransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestDelegateWithTransferCall from ABI bytes in the provided buffer
func (t *TestDelegateWithTransferCall) Decode(data []byte) (int, error) {
	if len(data) < 160 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 160
	// Decode static field Dest: address
	t.Dest, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field Delegator: address
	t.Delegator, _, err = abi.DecodeAddress(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field ValidatorAddr
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field ValidatorAddr")
		}
		t.ValidatorAddr, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Before: bool
	t.Before, _, err = abi.DecodeBool(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode static field After: bool
	t.After, _, err = abi.DecodeBool(data[128:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestDelegateWithTransferCall) GetMethodName() string {
	return "testDelegateWithTransfer"
}

// GetMethodID returns the function id
func (t TestDelegateWithTransferCall) GetMethodID() uint32 {
	return TestDelegateWithTransferID
}

// GetMethodSelector returns the function selector
func (t TestDelegateWithTransferCall) GetMethodSelector() [4]byte {
	return TestDelegateWithTransferSelector
}

// EncodeWithSelector encodes testDelegateWithTransfer arguments to ABI bytes including function selector
func (t TestDelegateWithTransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestDelegateWithTransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewTestDelegateWithTransferCall constructs a new TestDelegateWithTransferCall
func NewTestDelegateWithTransferCall(
	dest common.Address,
	delegator common.Address,
	validatorAddr string,
	before bool,
	after bool,
) *TestDelegateWithTransferCall {
	return &TestDelegateWithTransferCall{
		Dest:          dest,
		Delegator:     delegator,
		ValidatorAddr: validatorAddr,
		Before:        before,
		After:         after,
	}
}

// TestDelegateWithTransferReturn represents the output arguments for testDelegateWithTransfer function
type TestDelegateWithTransferReturn struct {
	abi.EmptyTuple
}
