// Code generated by go-abi. DO NOT EDIT.

package stakingreverter

import (
	"encoding/binary"
	"io"
	"math/big"

	cmn "github.com/cosmos/evm/precompiles/common"
	staking "github.com/cosmos/evm/precompiles/staking"
	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// callPrecompileBeforeAndAfterRevert(uint256,string)
	CallPrecompileBeforeAndAfterRevertSelector = [4]byte{0x92, 0x2a, 0x4b, 0x67}
	// getCurrentStake(string)
	GetCurrentStakeSelector = [4]byte{0x66, 0x8f, 0x45, 0x2b}
	// multipleDelegations(uint256,string)
	MultipleDelegationsSelector = [4]byte{0x52, 0xfc, 0xe7, 0xb1}
	// multipleQueries(uint256,address)
	MultipleQueriesSelector = [4]byte{0xcb, 0xc3, 0x67, 0xd4}
	// nestedTryCatchDelegations(uint256,uint256,string)
	NestedTryCatchDelegationsSelector = [4]byte{0x4d, 0x9d, 0xb9, 0x2b}
	// performDelegation(string)
	PerformDelegationSelector = [4]byte{0xf6, 0x60, 0x13, 0xd7}
	// run(uint256,string)
	RunSelector = [4]byte{0x4e, 0x5a, 0x8f, 0xe5}
)

// Big endian integer versions of function selectors
const (
	CallPrecompileBeforeAndAfterRevertID = 2452245351
	GetCurrentStakeID                    = 1720665387
	MultipleDelegationsID                = 1392306097
	MultipleQueriesID                    = 3418580948
	NestedTryCatchDelegationsID          = 1302182187
	PerformDelegationID                  = 4133491671
	RunID                                = 1314557925
)

var _ abi.Method = (*CallPrecompileBeforeAndAfterRevertCall)(nil)

const CallPrecompileBeforeAndAfterRevertCallStaticSize = 64

var _ abi.Tuple = (*CallPrecompileBeforeAndAfterRevertCall)(nil)

// CallPrecompileBeforeAndAfterRevertCall represents an ABI tuple
type CallPrecompileBeforeAndAfterRevertCall struct {
	NumTimes         *big.Int
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of CallPrecompileBeforeAndAfterRevertCall
func (t CallPrecompileBeforeAndAfterRevertCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddress)

	return CallPrecompileBeforeAndAfterRevertCallStaticSize + dynamicSize
}

// EncodeTo encodes CallPrecompileBeforeAndAfterRevertCall to ABI bytes in the provided buffer
func (value CallPrecompileBeforeAndAfterRevertCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := CallPrecompileBeforeAndAfterRevertCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field NumTimes: uint256
	if _, err := abi.EncodeUint256(value.NumTimes, buf[0:]); err != nil {
		return 0, err
	}

	// Field ValidatorAddress: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddress, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes CallPrecompileBeforeAndAfterRevertCall to ABI bytes
func (value CallPrecompileBeforeAndAfterRevertCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes CallPrecompileBeforeAndAfterRevertCall from ABI bytes in the provided buffer
func (t *CallPrecompileBeforeAndAfterRevertCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode static field NumTimes: uint256
	t.NumTimes, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field ValidatorAddress
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ValidatorAddress, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t CallPrecompileBeforeAndAfterRevertCall) GetMethodName() string {
	return "callPrecompileBeforeAndAfterRevert"
}

// GetMethodID returns the function id
func (t CallPrecompileBeforeAndAfterRevertCall) GetMethodID() uint32 {
	return CallPrecompileBeforeAndAfterRevertID
}

// GetMethodSelector returns the function selector
func (t CallPrecompileBeforeAndAfterRevertCall) GetMethodSelector() [4]byte {
	return CallPrecompileBeforeAndAfterRevertSelector
}

// EncodeWithSelector encodes callPrecompileBeforeAndAfterRevert arguments to ABI bytes including function selector
func (t CallPrecompileBeforeAndAfterRevertCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], CallPrecompileBeforeAndAfterRevertSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewCallPrecompileBeforeAndAfterRevertCall constructs a new CallPrecompileBeforeAndAfterRevertCall
func NewCallPrecompileBeforeAndAfterRevertCall(
	numTimes *big.Int,
	validatorAddress string,
) *CallPrecompileBeforeAndAfterRevertCall {
	return &CallPrecompileBeforeAndAfterRevertCall{
		NumTimes:         numTimes,
		ValidatorAddress: validatorAddress,
	}
}

// CallPrecompileBeforeAndAfterRevertReturn represents the output arguments for callPrecompileBeforeAndAfterRevert function
type CallPrecompileBeforeAndAfterRevertReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*GetCurrentStakeCall)(nil)

const GetCurrentStakeCallStaticSize = 32

var _ abi.Tuple = (*GetCurrentStakeCall)(nil)

// GetCurrentStakeCall represents an ABI tuple
type GetCurrentStakeCall struct {
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of GetCurrentStakeCall
func (t GetCurrentStakeCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddress)

	return GetCurrentStakeCallStaticSize + dynamicSize
}

// EncodeTo encodes GetCurrentStakeCall to ABI bytes in the provided buffer
func (value GetCurrentStakeCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := GetCurrentStakeCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field ValidatorAddress: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddress, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes GetCurrentStakeCall to ABI bytes
func (value GetCurrentStakeCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetCurrentStakeCall from ABI bytes in the provided buffer
func (t *GetCurrentStakeCall) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 32
	// Decode dynamic field ValidatorAddress
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ValidatorAddress, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t GetCurrentStakeCall) GetMethodName() string {
	return "getCurrentStake"
}

// GetMethodID returns the function id
func (t GetCurrentStakeCall) GetMethodID() uint32 {
	return GetCurrentStakeID
}

// GetMethodSelector returns the function selector
func (t GetCurrentStakeCall) GetMethodSelector() [4]byte {
	return GetCurrentStakeSelector
}

// EncodeWithSelector encodes getCurrentStake arguments to ABI bytes including function selector
func (t GetCurrentStakeCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], GetCurrentStakeSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewGetCurrentStakeCall constructs a new GetCurrentStakeCall
func NewGetCurrentStakeCall(
	validatorAddress string,
) *GetCurrentStakeCall {
	return &GetCurrentStakeCall{
		ValidatorAddress: validatorAddress,
	}
}

const GetCurrentStakeReturnStaticSize = 64

var _ abi.Tuple = (*GetCurrentStakeReturn)(nil)

// GetCurrentStakeReturn represents an ABI tuple
type GetCurrentStakeReturn struct {
	Shares  *big.Int
	Balance cmn.Coin
}

// EncodedSize returns the total encoded size of GetCurrentStakeReturn
func (t GetCurrentStakeReturn) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += t.Balance.EncodedSize()

	return GetCurrentStakeReturnStaticSize + dynamicSize
}

// EncodeTo encodes GetCurrentStakeReturn to ABI bytes in the provided buffer
func (value GetCurrentStakeReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := GetCurrentStakeReturnStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Shares: uint256
	if _, err := abi.EncodeUint256(value.Shares, buf[0:]); err != nil {
		return 0, err
	}

	// Field Balance: (string,uint256)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Balance.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes GetCurrentStakeReturn to ABI bytes
func (value GetCurrentStakeReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetCurrentStakeReturn from ABI bytes in the provided buffer
func (t *GetCurrentStakeReturn) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode static field Shares: uint256
	t.Shares, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Balance
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Balance.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*MultipleDelegationsCall)(nil)

const MultipleDelegationsCallStaticSize = 64

var _ abi.Tuple = (*MultipleDelegationsCall)(nil)

// MultipleDelegationsCall represents an ABI tuple
type MultipleDelegationsCall struct {
	NumTimes         *big.Int
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of MultipleDelegationsCall
func (t MultipleDelegationsCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddress)

	return MultipleDelegationsCallStaticSize + dynamicSize
}

// EncodeTo encodes MultipleDelegationsCall to ABI bytes in the provided buffer
func (value MultipleDelegationsCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := MultipleDelegationsCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field NumTimes: uint256
	if _, err := abi.EncodeUint256(value.NumTimes, buf[0:]); err != nil {
		return 0, err
	}

	// Field ValidatorAddress: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddress, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes MultipleDelegationsCall to ABI bytes
func (value MultipleDelegationsCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes MultipleDelegationsCall from ABI bytes in the provided buffer
func (t *MultipleDelegationsCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode static field NumTimes: uint256
	t.NumTimes, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field ValidatorAddress
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ValidatorAddress, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t MultipleDelegationsCall) GetMethodName() string {
	return "multipleDelegations"
}

// GetMethodID returns the function id
func (t MultipleDelegationsCall) GetMethodID() uint32 {
	return MultipleDelegationsID
}

// GetMethodSelector returns the function selector
func (t MultipleDelegationsCall) GetMethodSelector() [4]byte {
	return MultipleDelegationsSelector
}

// EncodeWithSelector encodes multipleDelegations arguments to ABI bytes including function selector
func (t MultipleDelegationsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], MultipleDelegationsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewMultipleDelegationsCall constructs a new MultipleDelegationsCall
func NewMultipleDelegationsCall(
	numTimes *big.Int,
	validatorAddress string,
) *MultipleDelegationsCall {
	return &MultipleDelegationsCall{
		NumTimes:         numTimes,
		ValidatorAddress: validatorAddress,
	}
}

// MultipleDelegationsReturn represents the output arguments for multipleDelegations function
type MultipleDelegationsReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*MultipleQueriesCall)(nil)

const MultipleQueriesCallStaticSize = 64

var _ abi.Tuple = (*MultipleQueriesCall)(nil)

// MultipleQueriesCall represents an ABI tuple
type MultipleQueriesCall struct {
	NumTimes         *big.Int
	ValidatorAddress common.Address
}

// EncodedSize returns the total encoded size of MultipleQueriesCall
func (t MultipleQueriesCall) EncodedSize() int {
	dynamicSize := 0

	return MultipleQueriesCallStaticSize + dynamicSize
}

// EncodeTo encodes MultipleQueriesCall to ABI bytes in the provided buffer
func (value MultipleQueriesCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := MultipleQueriesCallStaticSize // Start dynamic data after static section
	// Field NumTimes: uint256
	if _, err := abi.EncodeUint256(value.NumTimes, buf[0:]); err != nil {
		return 0, err
	}

	// Field ValidatorAddress: address
	if _, err := abi.EncodeAddress(value.ValidatorAddress, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes MultipleQueriesCall to ABI bytes
func (value MultipleQueriesCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes MultipleQueriesCall from ABI bytes in the provided buffer
func (t *MultipleQueriesCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field NumTimes: uint256
	t.NumTimes, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field ValidatorAddress: address
	t.ValidatorAddress, _, err = abi.DecodeAddress(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t MultipleQueriesCall) GetMethodName() string {
	return "multipleQueries"
}

// GetMethodID returns the function id
func (t MultipleQueriesCall) GetMethodID() uint32 {
	return MultipleQueriesID
}

// GetMethodSelector returns the function selector
func (t MultipleQueriesCall) GetMethodSelector() [4]byte {
	return MultipleQueriesSelector
}

// EncodeWithSelector encodes multipleQueries arguments to ABI bytes including function selector
func (t MultipleQueriesCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], MultipleQueriesSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewMultipleQueriesCall constructs a new MultipleQueriesCall
func NewMultipleQueriesCall(
	numTimes *big.Int,
	validatorAddress common.Address,
) *MultipleQueriesCall {
	return &MultipleQueriesCall{
		NumTimes:         numTimes,
		ValidatorAddress: validatorAddress,
	}
}

const MultipleQueriesReturnStaticSize = 32

var _ abi.Tuple = (*MultipleQueriesReturn)(nil)

// MultipleQueriesReturn represents an ABI tuple
type MultipleQueriesReturn struct {
	Validator staking.Validator
}

// EncodedSize returns the total encoded size of MultipleQueriesReturn
func (t MultipleQueriesReturn) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += t.Validator.EncodedSize()

	return MultipleQueriesReturnStaticSize + dynamicSize
}

// EncodeTo encodes MultipleQueriesReturn to ABI bytes in the provided buffer
func (value MultipleQueriesReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := MultipleQueriesReturnStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Validator: (string,string,bool,uint8,uint256,uint256,(string,string,string,string,string),int64,int64,uint256,uint256)
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = value.Validator.EncodeTo(buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes MultipleQueriesReturn to ABI bytes
func (value MultipleQueriesReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes MultipleQueriesReturn from ABI bytes in the provided buffer
func (t *MultipleQueriesReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 32
	// Decode dynamic field Validator
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		n, err = t.Validator.Decode(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*NestedTryCatchDelegationsCall)(nil)

const NestedTryCatchDelegationsCallStaticSize = 96

var _ abi.Tuple = (*NestedTryCatchDelegationsCall)(nil)

// NestedTryCatchDelegationsCall represents an ABI tuple
type NestedTryCatchDelegationsCall struct {
	OuterTimes       *big.Int
	InnerTimes       *big.Int
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of NestedTryCatchDelegationsCall
func (t NestedTryCatchDelegationsCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddress)

	return NestedTryCatchDelegationsCallStaticSize + dynamicSize
}

// EncodeTo encodes NestedTryCatchDelegationsCall to ABI bytes in the provided buffer
func (value NestedTryCatchDelegationsCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := NestedTryCatchDelegationsCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field OuterTimes: uint256
	if _, err := abi.EncodeUint256(value.OuterTimes, buf[0:]); err != nil {
		return 0, err
	}

	// Field InnerTimes: uint256
	if _, err := abi.EncodeUint256(value.InnerTimes, buf[32:]); err != nil {
		return 0, err
	}

	// Field ValidatorAddress: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddress, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes NestedTryCatchDelegationsCall to ABI bytes
func (value NestedTryCatchDelegationsCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes NestedTryCatchDelegationsCall from ABI bytes in the provided buffer
func (t *NestedTryCatchDelegationsCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 96
	// Decode static field OuterTimes: uint256
	t.OuterTimes, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field InnerTimes: uint256
	t.InnerTimes, _, err = abi.DecodeUint256(data[32:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field ValidatorAddress
	{
		offset, err = abi.DecodeSize(data[64:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ValidatorAddress, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t NestedTryCatchDelegationsCall) GetMethodName() string {
	return "nestedTryCatchDelegations"
}

// GetMethodID returns the function id
func (t NestedTryCatchDelegationsCall) GetMethodID() uint32 {
	return NestedTryCatchDelegationsID
}

// GetMethodSelector returns the function selector
func (t NestedTryCatchDelegationsCall) GetMethodSelector() [4]byte {
	return NestedTryCatchDelegationsSelector
}

// EncodeWithSelector encodes nestedTryCatchDelegations arguments to ABI bytes including function selector
func (t NestedTryCatchDelegationsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], NestedTryCatchDelegationsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewNestedTryCatchDelegationsCall constructs a new NestedTryCatchDelegationsCall
func NewNestedTryCatchDelegationsCall(
	outerTimes *big.Int,
	innerTimes *big.Int,
	validatorAddress string,
) *NestedTryCatchDelegationsCall {
	return &NestedTryCatchDelegationsCall{
		OuterTimes:       outerTimes,
		InnerTimes:       innerTimes,
		ValidatorAddress: validatorAddress,
	}
}

// NestedTryCatchDelegationsReturn represents the output arguments for nestedTryCatchDelegations function
type NestedTryCatchDelegationsReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*PerformDelegationCall)(nil)

const PerformDelegationCallStaticSize = 32

var _ abi.Tuple = (*PerformDelegationCall)(nil)

// PerformDelegationCall represents an ABI tuple
type PerformDelegationCall struct {
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of PerformDelegationCall
func (t PerformDelegationCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddress)

	return PerformDelegationCallStaticSize + dynamicSize
}

// EncodeTo encodes PerformDelegationCall to ABI bytes in the provided buffer
func (value PerformDelegationCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := PerformDelegationCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field ValidatorAddress: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddress, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes PerformDelegationCall to ABI bytes
func (value PerformDelegationCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PerformDelegationCall from ABI bytes in the provided buffer
func (t *PerformDelegationCall) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 32
	// Decode dynamic field ValidatorAddress
	{
		offset, err = abi.DecodeSize(data[0:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ValidatorAddress, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t PerformDelegationCall) GetMethodName() string {
	return "performDelegation"
}

// GetMethodID returns the function id
func (t PerformDelegationCall) GetMethodID() uint32 {
	return PerformDelegationID
}

// GetMethodSelector returns the function selector
func (t PerformDelegationCall) GetMethodSelector() [4]byte {
	return PerformDelegationSelector
}

// EncodeWithSelector encodes performDelegation arguments to ABI bytes including function selector
func (t PerformDelegationCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], PerformDelegationSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewPerformDelegationCall constructs a new PerformDelegationCall
func NewPerformDelegationCall(
	validatorAddress string,
) *PerformDelegationCall {
	return &PerformDelegationCall{
		ValidatorAddress: validatorAddress,
	}
}

// PerformDelegationReturn represents the output arguments for performDelegation function
type PerformDelegationReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*RunCall)(nil)

const RunCallStaticSize = 64

var _ abi.Tuple = (*RunCall)(nil)

// RunCall represents an ABI tuple
type RunCall struct {
	NumTimes         *big.Int
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of RunCall
func (t RunCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.ValidatorAddress)

	return RunCallStaticSize + dynamicSize
}

// EncodeTo encodes RunCall to ABI bytes in the provided buffer
func (value RunCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := RunCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field NumTimes: uint256
	if _, err := abi.EncodeUint256(value.NumTimes, buf[0:]); err != nil {
		return 0, err
	}

	// Field ValidatorAddress: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.ValidatorAddress, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes RunCall to ABI bytes
func (value RunCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes RunCall from ABI bytes in the provided buffer
func (t *RunCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err    error
		n      int
		offset int
	)
	dynamicOffset := 64
	// Decode static field NumTimes: uint256
	t.NumTimes, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field ValidatorAddress
	{
		offset, err = abi.DecodeSize(data[32:])
		if err != nil {
			return 0, err
		}
		if offset != dynamicOffset {
			return 0, abi.ErrInvalidOffsetForDynamicField
		}
		t.ValidatorAddress, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t RunCall) GetMethodName() string {
	return "run"
}

// GetMethodID returns the function id
func (t RunCall) GetMethodID() uint32 {
	return RunID
}

// GetMethodSelector returns the function selector
func (t RunCall) GetMethodSelector() [4]byte {
	return RunSelector
}

// EncodeWithSelector encodes run arguments to ABI bytes including function selector
func (t RunCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], RunSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// NewRunCall constructs a new RunCall
func NewRunCall(
	numTimes *big.Int,
	validatorAddress string,
) *RunCall {
	return &RunCall{
		NumTimes:         numTimes,
		ValidatorAddress: validatorAddress,
	}
}

// RunReturn represents the output arguments for run function
type RunReturn struct {
	abi.EmptyTuple
}
