name: Changelog Linter

on:
  pull_request:
    branches:
      - main
      - release/**
permissions: read-all

jobs:
  check_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check Changelog for changes
        uses: tarides/changelog-check-action@v3
        with:
          changelog: CHANGELOG.md