# Checks if a changelog is missing in the PR diff
name: Changelog Reminder
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    # Skip draft PRs and PRs starting with: revert, test, chore, ci, docs, style, build, refactor
    steps:
      - uses: actions/checkout@v4
      - uses: mskelton/changelog-reminder-action@v3
        with:
          message: "@${{ github.actor }} your pull request is missing a changelog!"
