on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths: [ "**/*.go" ]
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if CHANGELOG.md was modified
        run: |
          # Get the list of changed files in this PR
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          
          # Check if CHANGELOG.md (case insensitive) is in the changed files
          if echo "$CHANGED_FILES" | grep -qi "changelog\.md"; then
            echo "✅ CHANGELOG.md has been modified in this PR"
            echo "changelog_modified=true" >> $GITHUB_ENV
          else
            echo "❌ CHANGELOG.md has not been modified in this PR"
            echo "changelog_modified=false" >> $GITHUB_ENV
          fi

      - name: Fail if changelog not updated
        if: env.changelog_modified == 'false'
        run: |
          echo "::error::CHANGELOG.md must be updated for Go code changes"
          exit 1