name: "Dependency Review"
on: pull_request

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
          check-latest: true
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            *.toml
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v4
        if: env.GIT_DIFF
      - name: "Get govulncheck"
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        if: env.GIT_DIFF
      - name: Run govulncheck
        run: govulncheck -show verbose ./...
        shell: bash