name: Lint
# Lint runs golangci-lint over the entire Cosmos EVM repository
# This workflow runs on every pull request and push to main

on:
  pull_request:

# cancel superseded runs
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: depot-ubuntu-24.04-8
    timeout-minutes: 15
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true

      - uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Determine diff so we don't lint when no Go files are changed
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            *.toml

      - name: Run linting
        if: env.GIT_DIFF
        id: lint_long
        run: |
          make lint-go

  markdown-lint:
    name: markdownlint (cli2, minimal)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # operate on head when applicable
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      # only run if markdown or configs changed
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.md
            .markdownlint.yml
            .markdownlintignore

      # stable Node
      - uses: actions/setup-node@v4
        if: env.GIT_DIFF
        with:
          node-version: "20"

      # single pass: check; auto-fix for same-repo PRs (forks will fail)
      - name: markdownlint (check or fix)
        if: env.GIT_DIFF
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
          config: .markdownlint.yml
          fix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}

      # if fixes applied, commit & push
      - name: Push auto-fixes (PRs only)
        if: env.GIT_DIFF && github.event_name == 'pull_request'
        run: |
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "Auto-fix markdown lint issues"
            git push
          fi
